services:
  pibasho-frontend:
    image: redbugcollective/pibasho-frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /pibasho/www:/usr/share/nginx/html/apps
      - /pibasho/nginx/apps:/etc/nginx/conf.d/apps
    environment:
      - VIRTUAL_HOST=*.local
      - VIRTUAL_PATH=/admin/
      - VITE_API_HOST=/admin_backend
  pibasho-backend:
    image: redbugcollective/pibasho-backend
    expose:
      - "8000"
    environment:
      - VIRTUAL_HOST=*.local
      - VIRTUAL_PATH=/admin_backend/
      - VIRTUAL_DEST=/
      - ROCKET_LOG_LEVEL=debug
  scrib:
    image: redbugcollective/scrib
    expose:
      - "80"
    volumes:
      - /pibasho/www/books:/app/www
      - /pibasho/nginx/apps/scrib:/app/nginx
    environment:
      - VIRTUAL_HOST=*.local
      - VIRTUAL_PATH=/scrib/
      - VIRTUAL_DEST=/
