services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  pibasho-frontend:
    image: redbugcollective/pibasho-frontend
    expose:
      - "80"
    volumes:
      - /pibasho/apps:/usr/share/nginx/html/apps
      - /pibasho/nginx/apps:/etc/nginx/conf.d/apps
    environment:
      - VIRTUAL_HOST=*.local
      - VIRTUAL_PATH=/admin/
      - VITE_API_HOST=/admin_backend
  pibasho-backend:
    image: redbugcollective/pibasho-backend
    expose:
      - "8000"
    environment:
      - VIRTUAL_HOST=*.local
      - VIRTUAL_PATH=/admin_backend/
      - VIRTUAL_DEST=/
      - ROCKET_LOG_LEVEL=debug
  scrib:
    image: redbugcollective/scrib
    expose:
      - "80"
    volumes:
      - /pibasho/apps/scrib:/app/www
    environment:
      - VIRTUAL_HOST=*.local
      - VIRTUAL_PATH=/scrib/
      - VIRTUAL_DEST=/
