services:
  pibasho-frontend:
    image: resilientlocaltech/site-manager-frontend
    ports:
      - "8100:80"
      - "8101:443"
    # volumes:
    #   - /site-manager/www:/usr/share/nginx/html/apps
    #   - /site-manager/nginx/apps:/etc/nginx/conf.d/apps
    environment:
      - VIRTUAL_HOST=*.local
      - VIRTUAL_PATH=/admin/
      - VITE_API_HOST=/admin_backend
  pibasho-backend:
    image: resilientlocaltech/site-manager-backend
    ports:
      - "8102:8000"
    # volumes:
    #   - /site-manager/apps:/site-manager/apps
    environment:
      - VIRTUAL_HOST=*.local
      - VIRTUAL_PATH=/admin_backend/
      - VIRTUAL_DEST=/
      - ROCKET_LOG_LEVEL=debug
