services:
  lores-frontend:
    image: lores-frontend-dev
    ports:
      - "5173:5173"
    environment:
      - VITE_API_HOST=http://lores.localhost:8200
    volumes:
      - ./frontend/src:/app/src
  lores-node:
    image: lores-node-dev
    networks:
      - lores
    ports:
      - "8200:8200"
      - "2022:2022/udp"
      - "2023:2023/udp"
    environment:
      - FRONTEND_PATH=/app/frontend
      - DATABASE_URL=sqlite:/app/node_data/projections.sqlite
      - NODE_DATA_DATABASE_URL=sqlite:/app/node_data/node_data.sqlite
      - OPERATION_DATABASE_URL=sqlite:/app/node_data/operations.sqlite
      - CONFIG_PATH=/app/node_data/config.toml
      - APP_REPOS_PATH=/app/app_repos
      - APPS_PATH=/app/apps
      - HOST_OS_APPS_PATH=${HOST_OS_APPS_PATH}
      - BASE_URL=http://lores.localhost:5173
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend/data/app_repos:/app/app_repos
      - ./backend/data/apps:/app/apps
      - ./backend/data/node_data:/app/node_data
  traefik:
    logging:
      options:
        max-size: "1m"
    image: traefik:3.2
    networks:
      - lores
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
      - "443:443"
    command:
      - --accesslog=true
      # Possible log levels: DEBUG, INFO, WARN, ERROR (default), FATAL, PANIC
      - --log.level=DEBUG
      # Use your favourite settings here, but add:
      - --providers.swarm.network=lores
      - --providers.swarm.watch
      - --providers.swarm.exposedByDefault=false
      # By default a traefik-enabled service can be accessed at
      # https://stackName.TOP_DOMAIN (where TOP_DOMAIN is specified at
      # the proxy stack's create time, or set to 'localhost' by default.
      - --providers.swarm.defaultRule=Host(`lores.localhost`)
      - --api
      - --entryPoints.web.address=:80
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.api.rule: Host(`traefik.${TOP_DOMAIN:-localhost}`)
        traefik.http.routers.api.entryPoints: web
        traefik.http.routers.api.service: api@internal
        # traefik.http.routers.api.middlewares: auth
        traefik.http.services.dummy.loadbalancer.server.port: 4242
        # echo $(htpasswd -nB user) | sed -e s/\\$/\\$\\$/g
networks:
  lores:
    name: lores
    driver: overlay
    attachable: true
