[package]
name = "lores-node"
version = "0.24.0"
edition = "2024"
rust-version = "1.96"
publish = false

[dependencies]
anyhow = "1.0"
axum = { version = "0.8", features = ["ws"] }
axum-login = "0.18"
chrono = { version = "0.4", features = ["serde"] }
confy = "2.0"
futures-util = "0.3"
lazy_static = "1.5"
password-auth = "1.0"
pwgen2 = "0.8"
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0"
short-uuid = "0.2"
sqlx = { workspace = true, features = [
  "runtime-tokio",
  "tls-native-tls",
  "sqlite",
  "chrono",
] }
thiserror = { workspace = true }
time = "0.3"
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tower = "0.5"
tower-http = { version = "0.7", features = ["cors", "fs", "trace"] }
tower-sessions = { version = "0.15", features = ["signed"] }
tower-sessions-sqlx-store = { version = "0.15", features = ["sqlite"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
utoipa = "6.0"
utoipa-axum = "0.3"
utoipa-swagger-ui = { version = "10.0", features = ["axum", "vendored"] }
hex = { workspace = true }
lores-p2panda = { path = "../lores-p2panda" }
lores-p2panda-server = { path = "../lores-p2panda-server" }
coop-cloud-docker-apps = { path = "../coop-cloud-docker-apps" }
p2panda-core = { workspace = true }
tonic = { workspace = true }
rand = "0.10"
regex = "1.12"
