[package]
name = "lores-dev-server"
version = "0.1.0"
authors = ["Jade Ambrose", "Merri-bek Tech Inc."]
edition = "2024"
rust-version = "1.96"
description = "In-memory development gRPC server for the lores-p2panda API."
readme = "README.md"
homepage = "https://lores.tech/"
repository = "https://github.com/local-resilience-tech/lores-node/"
keywords = ["p2p", "lores", "p2panda", "grpc", "dev-server"]
categories = ["network-programming", "development-tools"]
publish = true
license-file = "LICENSE.md"

[[bin]]
name = "lores-dev-server"
path = "src/main.rs"

[dependencies]
futures = "0.3"
hex = { workspace = true }
sha2 = "0.10"
prost = "0.14"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync"] }
tokio-stream = { version = "0.1", features = ["sync"] }
tonic = "0.14"
tonic-prost = "0.14"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[build-dependencies]
tonic-prost-build = "0.14"
