---
- name: Ensure that the example app directory exists
  ansible.builtin.file:
    path: "{{ host_apps_path }}/example"
    state: directory
    mode: "0755"

- name: Copy the config directory for the app example
  ansible.builtin.copy:
    src: ../apps/example/config/
    dest: "{{ host_apps_path }}/example/config"
    mode: "0644"

- name: Copy the compose file for the app example
  ansible.builtin.copy:
    src: ../apps/example/compose.yml
    dest: "{{ host_apps_path }}/example/compose.yml"
    mode: "0644"

- name: Deploy example app
  community.docker.docker_stack:
    state: present
    name: lores-app-example
    detach: false
    compose:
      - "{{ host_apps_path }}/example/compose.yml"
      - version: "1.0"
        services:
          web:
            volumes:
              - "{{ host_apps_path }}/example/config:/{{client_config_path}}"
