[package]
name = "lores-p2panda"
version = "0.23.0"
edition = "2024"
rust-version = "1.96"
publish = false

[dependencies]
p2panda = { workspace = true }
p2panda-core = { workspace = true }
p2panda-encryption = { workspace = true }
p2panda-net = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0"
sqlx = { workspace = true, default-features = false, features = [
  "runtime-tokio",
  "sqlite",
] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tokio-stream = { workspace = true }
tracing = "0.1"
hex = { workspace = true }
rand = "0.10"

[dev-dependencies]
tempfile = "3"
