---
- hosts:
    - cloud.nodes.merri-bek.tech
  roles:
    - docker_swarm_manager
    - traefik
    - shepherd
    - lores_node
    - app_example
  vars:
    host_apps_path: /etc/lores-node/apps
    client_config_path: /lores_config
