- name: Ensure Watchtower stack is configured
  community.docker.docker_stack:
    state: present
    name: watchtower
    compose:
      - services:
          watchtower:
            image: containrrr/watchtower
            command:
              - --label-enable
              - --interval=30
            volumes:
              - /var/run/docker.sock:/var/run/docker.sock
