name: Publish Docker image

on:
  push
  # release:
  #   types: [published]

jobs:
  build-and-push:
    name: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}