name: Publish Docker image

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  build-and-push:
    name: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker

      - name: Checkout
        uses: actions/checkout@v4

      - name: Get ref
        id: parse_ref
        run: |
          echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7
          push: true
          tags: |
            redbugcollective/${{ github.repository }}:latest
            redbugcollective/${{ github.repository }}:${{ steps.parse_ref.outputs.tag }}