name: Publish Docker image

on:
  push:
    tags: ["v*.*.*"]

jobs:
  build-frontend-and-backend:
    name: build-frontend-and-backend
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout
        uses: actions/checkout@v4

      - name: Get ref
        id: parse_ref
        run: |
          echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push combined
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/site-manager:latest,${{ secrets.DOCKERHUB_USERNAME }}/site-manager:${{ steps.parse_ref.outputs.tag }}
